## Generated by `roc scripts/tasks.roc css`. Do not edit by hand.

AssetVersions := [].{
	appIcon : Str
	appIcon = "08d26ab05aaf724222c4c0cd5a19d5eae753b2a5fff0eb2d81759dde11bac6b6"

	hero480 : Str
	hero480 = "ab003e7cce23cc4e7ccd1c74b1c5c964d7f4e91571c8c6127da824cb3e0138aa"

	hero640 : Str
	hero640 = "accca16bc5c0bf545228b33f357b691934db894694df60c1da0bebb5d3ff8404"

	hero720 : Str
	hero720 = "6b9aaad44c71b8a64d863cac511140d54dc2ae92d6f0beb79e43792196dc7ae7"

	hero960 : Str
	hero960 = "88c8d6045036e7c8e6ee8130c4690dadfd915506d362352029a9cd9fdbe7d15c"

	htmx : Str
	htmx = "28fae7bbe8e8142b702debb9d5234a9a436d9435a4b5165b195aa1a7ed840d25"

	interactions : Str
	interactions = "34532b92e0cc14a652e97eb7f0d9bdbe8426432f1eaa254706b785d781ea7b6a"

	stylesheet : Str
	stylesheet = "268cfbc1d0f4efea89c5a0b979164b695565e69feb77c3a4cbd335cd61f6bd1b"
}
